### ISSUE TITLE
CRUD functions

### ISSUE THREAD

**Issue by Henrikbj1990** [Henrikbj1990/Mandatory-MEAN#2]
CRUD functions for:
- Users
- Content
- Categories
- Tags
- If a commenting feature is implemented on the frontend, it shall be possible to perform
  administration on these as well in the backend.

**Comment by nstruds** [comment]
Delete user is done

**Comment by nstruds** [comment]
Der er lavet read, delete, create og edit User

**Comment by nstruds** [comment]
Done
